### ISSUE TITLE
Ask for SSH Port default to 22

### ISSUE THREAD

**Issue by flemming-pr** [visuellverstehen/pull#9]

**Comment by malteriechmann** [comment]
@flemming-petersen Can you maybe provide a bit context?

**Comment by flemming-pr** [comment]
We do have some projects where the SSH port is not the default 22. 
In order to connect to those servers we need to add a port option.

**Comment by malteriechmann** [comment]
Ah, alright. So we should add a variable `$remoteServerPort` and default it to 22.

Makes sense :)

**Comment by flemming-pr** [comment]
This is what I am working on ;)
